version: '3.7'
name: pizza

services:
  frontend_cra:
    container_name: pizza_frontend
    image: pizza_frontend:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  backend:
    container_name: pizza_api
    image: pizza_api:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Backend/Backend.API/Dockerfile
    volumes:
      - ./Backend/Backend.API:/src
      - /src/obj/
      - /src/bin/
      - .certs:/certs
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+:443;http://+:80'
      ASPNETCORE_Kestrel__Certificates__Default__Path: /certs/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /certs/localhost.key
    ports:
      - "44444:80"
      - "44445:443"
    working_dir: /src
networks:
  default:
    name: pizza

