services:
  frontend:
      build:
        context: .
        dockerfile: frontend/Dockerfile
        target: dev
      volumes:
        - ./frontend:/app
        - /app/node_modules
  backend:
      build:
        context: .
        dockerfile: Backend/Backend.API/Dockerfile
        target: dev