version: '3.7'
name: pizza

services:
  frontend:
    container_name: pizza_frontend
    image: nadegamra.azurecr.io/pizza_frontend:1.0
    restart: unless-stopped
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
  backend:
    container_name: pizza_api
    image: nadegamra.azurecr.io/pizza_api:1.0
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: 'https://+:443;http://+:80'
      ASPNETCORE_Kestrel__Certificates__Default__Path: /certs/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /certs/localhost.key
    working_dir: /src
  proxy:
    container_name: proxy
    image: nadegamra.azurecr.io/pizza_proxy:1.0
    build: .
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
networks:
  default:
    name: pizza