services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true   
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: 
      context: .
      dockerfile: Backend/Backend.API/Dockerfile.dev
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    volumes:
      - ./Backend/Backend.API:/src
      - /src/obj/
      - /src/bin/
      - .certs:/certs